---
    version: "2.1"
    services:
      keycloak:
        image: jboss/keycloak
        container_name: keycloak
        environment:
          - KEYCLOAK_USER=
          - KEYCLOAK_PASSWORD=
          - KEYCLOAK_FRONTEND_URL=https://keycloak.ca-hd.net/auth/
      swag:
        image: ghcr.io/linuxserver/swag
        container_name: swag
        cap_add:
          - NET_ADMIN
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/Berlin
          - URL=ca-hd.net
          - SUBDOMAINS=www,cloud,wiki,chat,keycloak,heimdall
          - VALIDATION=http
        volumes:
          - /home/aptalca/appdata/swag:/config
        ports:
          - 443:443
          - 80:80
        restart: unless-stopped
      dokuwiki:
        image: ghcr.io/linuxserver/dokuwiki
        container_name: dokuwiki
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/Berlin
        volumes:
          - /path/to/appdata/config:/config
        restart: unless-stopped
      nextcloud:
        image: ghcr.io/linuxserver/nextcloud
        container_name: nextcloud
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/Berlin
        volumes:
          - /path/to/appdata:/config
          - /path/to/data:/data
        restart: unless-stopped
      heimdall:
        image: ghcr.io/linuxserver/heimdall
        container_name: heimdall
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
        volumes:
          - /path/to/appdata/config:/config
        restart: unless-stopped
      rocketchat:
        image: rocketchat/rocket.chat:latest
        container_name: rocketchat
        depends_on:
          - mongo_rocketchat
        environment:
          - ROOT_URL=http://chat.ca-hd.net/
          - MONGO_URL=mongodb://mongo:27017/rocketchat
          - MONGO_OPLOG_URL=mongodb://mongo:27017/local
        volumes:
          - ./uploads:/app/uploads
        restart: unless-stopped
      mongo_rocketchat:
        image: mongo:4.0
        container_name: mongo_rocketchat
        restart: unless-stopped
        volumes:
          - ./data/db/:/data/db
        command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1